include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    always_declare_return_types: true
    avoid_empty_else: true
    use_rethrow_when_possible: true