name: unice_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  app_links: 6.4.0
  get_it:
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  path_provider:
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.15
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  injectable:
  flutter_bloc: ^8.1.6
  go_router: ^14.8.0
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0
  device_info_plus: ^11.1.1
  path: ^1.9.0
  http_parser: ^4.1.2
  introduction_screen: ^3.1.16
  translator: ^1.0.3+1
  percent_indicator: ^4.2.4
  google_sign_in: ^6.2.2
  http: ^1.3.0
  stream_video: ^0.8.4
  stream_video_flutter: ^0.8.4
  stream_video_push_notification: ^0.8.4
  reown_appkit: ^1.4.3+1
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  mobile_scanner: ^6.0.7
  firebase_core: ^3.13.0
  firebase_app_check: ^0.3.2+5
  toastification: ^3.0.2
  screenshot: ^3.0.0
  socket_io_client: ^3.1.1
  gallery_saver_plus: ^3.2.4
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  qr_code_tools: ^0.2.0
  flutter_ringtone_player: ^4.0.0+4
  flutter_sound: ^9.28.0
  sign_in_with_apple: ^7.0.1
  pin_code_fields: ^8.0.1

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner:
  drift_dev: ^2.23.1
  injectable_generator:

flutter:
  uses-material-design: true
  generate: true
    - gen_l10n


  assets:
    - env/
    - assets/svg/
    - assets/png/
    - assets/font/
    - assets/lottie/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
